### ISSUE TITLE
toJSON not found on string

### ISSUE THREAD

**Issue by rafal-ksiazek-rmtcfm-com** [gmlazu/swagger-to-static#2]
There is no toJSOn method on string.

We should use JSON.parse(string);

**Comment by rafal-ksiazek-rmtcfm-com** [comment]
PR is waiting: https://github.com/gmlazu/swagger-to-static/pull/1

**Comment by lageorgem** [comment]
Hello! I am extremely sorry for such a late reply, unfortunately I haven't really touched this small project until now. And I had the same problem as you! A very pleasant surprize that someone has already fix it :).
